"""Render the theorem table directly from the admitted certificate artifacts."""

from __future__ import annotations

from decimal import Decimal, localcontext
from fractions import Fraction
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CERTIFICATE = ROOT / "data/certificate.json"
PROPAGATION = ROOT / "data/recentered_tail_propagation.json"
OUTPUT = ROOT / "manuscript/generated_certificate_table.tex"


def fraction(value: object) -> Fraction:
    if isinstance(value, dict):
        return Fraction(value["numerator"], value["denominator"])
    return Fraction(str(value))


def scientific(value: Fraction, digits: int = 6) -> str:
    with localcontext() as context:
        context.prec = 80
        rendered = format(
            Decimal(value.numerator) / Decimal(value.denominator), f".{digits}E"
        )
    coefficient, exponent = rendered.split("E")
    return rf"${coefficient}\times10^{{{int(exponent)}}}$"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    certificate = json.loads(CERTIFICATE.read_text(encoding="utf-8"))
    propagation = json.loads(PROPAGATION.read_text(encoding="utf-8"))
    finite = certificate["finite_source_sector"]["recentered_krawczyk"]
    radius = fraction(finite["box_radius"])
    displacement = fraction(finite["maximum_center_displacement_upper"])
    remainder = fraction(finite["maximum_remainder_row_sum_upper"])
    base_image = displacement + remainder * radius
    margin = radius - base_image
    tail = fraction(propagation["maximum_componentwise_added_radius_upper"])
    c_norm = fraction(propagation["preconditioner"]["infinity_norm_upper"])
    counts = certificate["degree_coverage"]["category_counts"]
    rows = [
        ("Complex fields / real equations", "6 / 12"),
        ("Finite source rows", str(certificate["finite_source_sector"]["published_degrees"])),
        ("Low-total representations", str(certificate["degree_coverage"]["representation_count"])),
        ("Partition $Z/S/M/U$", f"{counts['chow_zero']}/{counts['source_table']}/{counts['displayed_multicover']}/{counts['uncovered']}"),
        ("Box radius $r$", scientific(radius)),
        (r"$\lVert C F(x_0)\rVert_\infty$", scientific(displacement)),
        (r"$\lVert I-CJ(X)\rVert_\infty$", scientific(remainder)),
        ("Finite Krawczyk image", scientific(base_image)),
        ("Finite strict margin", scientific(margin)),
        (r"$\lVert C_{\rm new}\rVert_\infty$", scientific(c_norm)),
        ("Maximum all-orders addition", scientific(tail)),
        ("Tail / finite margin", scientific(tail / margin)),
        ("Strict real components", "12"),
        ("Authenticated provenance files", str(len(certificate["provenance"]))),
    ]
    lines = [
        "% Generated by scripts/render_certificate_table.py; do not edit by hand.",
        rf"% certificate sha256: {sha256(CERTIFICATE)}",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{@{}lr@{}}",
        "\\toprule",
        "Certified quantity & Value\\\\",
        "\\midrule",
    ]
    lines.extend(f"{label} & {value}\\\\" for label, value in rows)
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Machine-generated summary of the admitted certificate. The",
        "displayed decimals are derived from exact rational bounds.}",
        "\\label{tab:certificate}",
        "\\end{table}",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
